name: rider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  country_code_picker: ^3.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.1
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
