name: rider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  get: ^4.7.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.1
  lottie: ^3.1.3
  pinput: ^5.0.0  
  country_code_picker: ^3.1.0
  flutter_rating_stars: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  encrypt: ^5.0.3
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1
  cherry_toast: ^1.12.0
  google_maps_flutter: ^2.10.0
  socket_io_client: ^3.0.2
  onesignal_flutter: ^5.3.2
  geolocator: ^13.0.2
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/  
